export const NVIDIANIM_BASE_URL = "https://integrate.api.nvidia.com/v1"
export const nvidiaNimDefaultModelId = "meta/llama-3.3-70b-instruct"
export const nvidiaNimModels = {
	// AbacusAI
	"abacusai/dracarys-llama-3.1-70b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Dracarys-LLaMA-3.1-70B-Instruct by AbacusAI",
	},
	// Bytedance
	"bytedance/seed-oss-36b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Seed-OSS-36B-Instruct by Bytedance",
	},
	// DeepSeek
	"deepseek-ai/deepseek-v4-flash": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "DeepSeek V4 Flash by DeepSeek AI",
	},
	"deepseek-ai/deepseek-v4-pro": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "DeepSeek V4 Pro by DeepSeek AI",
	},
	// Google
	"google/codegemma-7b": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "CodeGemma 7B by Google",
	},
	"google/gemma-2-2b-it": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Gemma 2 2B IT by Google",
	},
	"google/gemma-7b": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Gemma 7B by Google",
	},
	// Meta
	"meta/llama2-70b": {
		maxTokens: 4096,
		contextWindow: 4096,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 2 70B by Meta",
	},
	"meta/llama-3.1-8b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 8B Instruct by Meta",
	},
	"meta/llama-3.1-70b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 70B Instruct by Meta",
	},
	"meta/llama-3.2-1b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.2 1B Instruct by Meta",
	},
	"meta/llama-3.2-3b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.2 3B Instruct by Meta",
	},
	"meta/llama-3.3-70b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.3 70B Instruct by Meta",
	},
	// Microsoft
	"microsoft/phi-4-mini-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Phi-4 Mini Instruct by Microsoft",
	},
	"microsoft/phi-4-mini-flash-reasoning": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Phi-4 Mini Flash Reasoning by Microsoft",
	},
	// MiniMax
	"minimaxai/minimax-m2.5": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "MiniMax M2.5 by MiniMax AI",
	},
	"minimaxai/minimax-m2.7": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "MiniMax M2.7 by MiniMax AI",
	},
	// Mistral
	"mistralai/mistral-nemotron": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Mistral Nemotron by Mistral AI",
	},
	"mistralai/mixtral-8x7b-instruct": {
		maxTokens: 8192,
		contextWindow: 32_768,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Mixtral 8x7B Instruct by Mistral AI",
	},
	"mistralai/mixtral-8x22b-instruct": {
		maxTokens: 8192,
		contextWindow: 65_536,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Mixtral 8x22B Instruct by Mistral AI",
	},
	// Moonshot
	"moonshotai/kimi-k2-instruct": {
		maxTokens: 16384,
		contextWindow: 262_144,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.6,
		outputPrice: 2.5,
		cacheReadsPrice: 0.15,
		description: "Kimi K2 Instruct by Moonshot AI",
	},
	"moonshotai/kimi-k2-thinking": {
		maxTokens: 16384,
		contextWindow: 262_144,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.6,
		outputPrice: 2.5,
		cacheReadsPrice: 0.15,
		supportsTemperature: true,
		preserveReasoning: true,
		defaultTemperature: 1.0,
		description: "Kimi K2 Thinking by Moonshot AI",
	},
	// NVIDIA
	"nvidia/gliner-pii": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "GLiNER PII by NVIDIA",
	},
	"nvidia/llama-3.1-nemoguard-8b-content-safety": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 Nemoguard 8B Content Safety by NVIDIA",
	},
	"nvidia/llama-3.1-nemoguard-8b-topic-control": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 Nemoguard 8B Topic Control by NVIDIA",
	},
	"nvidia/nemotron-3-ultra-550b-a55b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Nemotron 3 Ultra 550B-a55b by NVIDIA",
	},
	"nvidia/llama-3.1-nemotron-nano-8b-v1": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 Nemotron Nano 8B V1 by NVIDIA",
	},
	"nvidia/llama-3.1-nemotron-safety-guard-8b-v3": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 Nemotron Safety Guard 8B V3 by NVIDIA",
	},
	"nvidia/llama-3.3-nemotron-super-49b-v1": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.3 Nemotron Super 49B V1 by NVIDIA",
	},
	"nvidia/llama-3.3-nemotron-super-49b-v1.5": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.3 Nemotron Super 49B V1.5 by NVIDIA",
	},
	"nvidia/llama-3.1-nemotron-ultra-253b-v1": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "LLaMA 3.1 Nemotron Ultra 253B V1 by NVIDIA",
	},
	"nvidia/nemoguard-jailbreak-detect": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Nemoguard Jailbreak Detect by NVIDIA",
	},
	"nvidia/nemotron-3-nano-30b-a3b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Nemotron 3 Nano 30B-a3b by NVIDIA",
	},
	"nvidia/nemotron-3-super-120b-a12b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Nemotron 3 Super 120B-a12b by NVIDIA",
	},
	"nvidia/nemotron-content-safety-reasoning-4b": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Nemotron Content Safety Reasoning 4B by NVIDIA",
	},
	"nvidia/nemotron-mini-4b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Nemotron Mini 4B Instruct by NVIDIA",
	},
	"nvidia/nvidia-nemotron-nano-9b-v2": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "NVIDIA Nemotron Nano 9B V2",
	},
	"nvidia/riva-translate-4b-instruct-v1_1": {
		maxTokens: 8192,
		contextWindow: 8192,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Riva Translate 4B Instruct V1.1 by NVIDIA",
	},
	"nvidia/usdcode": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "USDCode by NVIDIA",
	},
	// OpenAI
	"openai/gpt-oss-20b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "GPT OSS 20B by OpenAI",
	},
	"openai/gpt-oss-120b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "GPT OSS 120B by OpenAI",
	},
	// Qwen
	"qwen/qwen2.5-coder-32b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Qwen 2.5 Coder 32B Instruct by Alibaba",
	},
	"qwen/qwen3.5-122b-a10b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Qwen 3.5 122B-a10b by Alibaba",
	},
	"qwen/qwen3-coder-480b-a35b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Qwen 3 Coder 480B-a35b Instruct by Alibaba",
	},
	"qwen/qwen3-next-80b-a3b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Qwen 3 Next 80B-a3b Instruct by Alibaba",
	},
	"qwen/qwen3-next-80b-a3b-thinking": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Qwen 3 Next 80B-a3b Thinking by Alibaba",
	},
	"qwen/qwq-32b": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "QwQ 32B by Alibaba",
	},
	// Sarvam
	"sarvamai/sarvam-m": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Sarvam M by Sarvam AI",
	},
	// StepFun
	"stepfun-ai/step-3-5-flash": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Step 3.5 Flash by StepFun AI",
	},
	// Stockmark
	"stockmark/stockmark-2-100b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Stockmark 2 100B Instruct by Stockmark",
	},
	// Upstage
	"upstage/solar-10.7b-instruct": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "Solar 10.7B Instruct by Upstage",
	},
	// Z-AI
	"z-ai/glm4.7": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "GLM 4.7 by Z-AI",
	},
	"z-ai/glm5.1": {
		maxTokens: 8192,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "GLM 5.1 by Z-AI",
	},
	"z-ai/glm-5.2": {
		maxTokens: 16384,
		contextWindow: 131_072,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.88,
		outputPrice: 0.88,
		description: "GLM 5.2 by Z-AI",
	},
}
